### ISSUE TITLE
Mapping to sealed class

### ISSUE THREAD

**Issue by WoodyMKD** [netglade/auto_mappr#124]
Hey, 

I've stumbled upon this library a couple of days ago and it looks awesome! I'm experimenting at the moment and so far i was able to make it work with every case i've tried, except one. 

I have a Data Model:
```
@freezed
class ExtendedContactDataModel with _$ExtendedContactDataModel {
  const factory ExtendedContactDataModel({
    required String id,
    required String? phoneNumber,
    required String? remoteId,
    required String name,
  }) = _ExtendedContactDataModel;
}
```

And a sealed class (Domain model)
```
@freezed
sealed class ContactModel with _$ContactModel {
  const factory ContactModel.phonebook({
    required final String id,
    required final String name,
    required final String phoneNumber,
  }) = PhonebookContact;

  const factory ContactModel.synced({
    required final String id,
    required final String name,
    required final String remoteId,
  }) = SyncedContact;

  factory ContactModel.fromData({
    required final String id,
    required final String? remoteId,
    required final String name,
    required final String? phoneNumber,
  }) {
    if (remoteId == null) {
      return ContactModel.phonebook(
        id: id,
        name: name,
        phoneNumber: phoneNumber,
      );
    } else {
      return ContactModel.synced(
        id: id,
        remoteId: remoteId,
        name: name,
      );
    }
  }
}
```

Unfortunately, the generated code from automappr is missing the phonenumber and remoteId:
```
    return _i8.ContactModel.fromData(
      id: model.id,
      name: model.name,
    );
```

And here is the definition:
```
mappr.MapType<ExtendedContactDataModel, ContactModel>(
    constructor: 'fromData',
)

**Comment by tenhobi** [comment]
Hi, so I checked this case and it seems it's more less the same like situation mentioned in https://github.com/netglade/auto_mappr/issues/29.

Basically, this package states that it works with freezed, meaning that it can be both used together. Mapping have to be however specified on case to case basis, since I am not sure we can easily generate code that would support mapping of essentially disjunctive cases. So don't try to tell mappr "map A or B or C or D or E... into X or Y or Z..." but rather "map A to X, map B to Y, map C to Z, ..." and that will be both more clear to you as it will do exactly what you want anytime and also mappr don't have to do some black magic and guess :D 

Similar thing also applies to sealed classes, where you also don't want to use that sealed class as a source or target but map it's specific types. We should probably clarify that more in docs. 🤔

**Comment by tenhobi** [comment]
Since it's a week without a response, I am closing the issue now. Feel free to reopen the discussion.
