### ISSUE TITLE
Nullable input/output with type converters

### ISSUE THREAD

**Issue by tenhobi** [netglade/auto_mappr#128]
Type converters in `MapType` and `@AutoMappr` right now accept only `<Object, Object>` (`final List<TypeConverter<Object, Object>> converters;`).
While this makes sense for mappings, for type converters we want to distinguish and be able to handle nullable types, ergo the contract should probably be `<Object?, Object?>` and the logic behind type converters should be enhanced to support that.

This is for cases when I have a converter for String to DateTime, but the source/target is nullable. For example, it would pass source String? to that converter which ends in a type mismatch.

Implementation is straightforward, just keep in mind that:
In cases when `Object` is expected (source or target) and a type converter is set with `Object?`, this converter should handle it.
In cases when `Object?` is expected (source or target) and a type converter is set with `Object`, this converter should not be used.

**Comment by ekerik220** [comment]
I need this functionality so I took a look at the code and I think I see how this could be implemented. I want to clarify the requirements though, if possible.

> In cases when Object is expected (source or target) and a type converter is set with Object?, this converter should handle it.

Does this mean if we had a `TypeConverter<Object?, Object?>` it can be used for all conversions?
- Object -> Object
- Object -> Object?
- Object? -> Object
- Object? -> Object?

I think anything with `-> Object` could be a problem for this type converter, since the function that will handle the conversion could possibly return null. I think it's reasonable for it handle both `Object ->` and `Object? ->` though, since the conversion function would be built to handle a nullable input, which can also be used to handle a non-nullable input just fine.

> In cases when Object? is expected (source or target) and a type converter is set with Object, this converter should not be used.

So in this case, if we had a type converter `TypeConverter<Object, Object>`, it would not be usable to any conversions that have a nullable source or target? I think it could technically handle `-> Object?` conversions as well, since the non-null value returned by the conversion function could still be assigned to a nullable variable, but I'm not sure if it _should_ handle it or not.

So I think maybe there is a design choice to be made. TypeConverters with nullable generics can technically handle some non-nullable cases safely, and TypeConverters with non-nullable generics can technically handle some nullable cases safely, but I guess the decision is whether they _should_ or not. We could make them really strict so that the type and the nullability of the type has to match exactly, and that might be easier to understand for someone using the API, but it would also mean that their code might have to be more verbose to cover all the scenarios they need.

What do you think?

**Comment by tenhobi** [comment]
Hi @ekerik220 thanks for your initiative! Hmm, you are probably right. Thinking about it more, should it work like this?:

Aka choosing the solution that works the same way as if you had some converter function and manually using it in code.

- `TypeConverter<Object, Object>`
  - `Object` -> `Object`
  - `Object` -> `Object?`
- `TypeConverter<Object, Object?>`
  - `Object` -> `Object?`
- `TypeConverter<Object?, Object>`
  - `Object` -> `Object`
  - `Object?` -> `Object`
  - `Object` -> `Object?`
  - `Object?` -> `Object?`
- `TypeConverter<Object?, Object?>`
  - `Object` -> `Object?`
  - `Object?` -> `Object?`
  
So the most universal type converter that can handle every case will be `TypeConverter<Object?, Object>` probably?
  
**This enhancement should be well-tested for sure.**

**Comment by ekerik220** [comment]
That looks good to me! For sure, this enhancement has a lot of possible cases so all of the cases should be tested.

Do you have any suggestions on how this should be tested? I think generating and using a mapper like in the current integration tests gets us part of the way there, and maybe unit testing `TypeConverter.canBeUsed` would be good too.

I made a quick implementation that I think might work. No tests yet, but let me know if you think it should be done differently or if I'm missing something. #130

**Comment by tenhobi** [comment]
So released in auto_mappr 2.1.1 and auto_mappr_annotation 2.1.0 🎉

**Comment by ekerik220** [comment]
Thanks for your quick reviews and release! I'm using the feature now.  🎉
